name: CI/CD Pipeline for Streamlit Calculator

on:
  push:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          pip install streamlit selenium webdriver-manager
      - name: Run Unit Tests
        run: python test_app.py
      - name: Build Docker Image
        run: docker build -t calculator-app:v1 .

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
      - uses: actions/checkout@v3
      - name: Simulate Deployment
        run: echo "Deployment would happen here (e.g., push to registry and deploy)"
